### ISSUE TITLE
Root package version

### ISSUE THREAD

**Issue by borisdamevin** [ext/semantic-release-lerna#63]
Hi @ext 

Can we disabled the `version` update on root `package.json`?

With Lerna, only sub `package.json` versions are important and if we don't want poluate the root `package.json` for any reason is better to have a choice.

Thank you.

**Comment by ext** [comment]
Sure, would you mind creating a PR? It would probably be as simple as adding an if-statement around [lib/prepare.js#L218](https://github.com/ext/semantic-release-lerna/blob/master/lib/prepare.js#L218) (and writing a test-case)

**Comment by borisdamevin** [comment]
Release on version 0.6.0.
