### ISSUE TITLE
Issue with github actions

### ISSUE THREAD

**Issue by borisdamevin** [ext/semantic-release-lerna#69]
@ext 

I have issue with Guithub actions

![image](https://user-images.githubusercontent.com/1703605/176179546-c379405a-d495-4793-85df-d7f119161203.png)

**Comment by ext** [comment]
Is `package-lock.json` present in `assets` in the configuration for `"@semantic-release/git"`?

Interestingly enough this comes from the `verifyConditions` stage, do you happen to know what the changes are? E.g. are you able to run `git diff` somehow? Is it possible it comes from `npm install`?

**Comment by borisdamevin** [comment]
Hi @ext 

It's present, I try on another repo for testing and the stage pass. So I don't understand why `package-lock.json` not validated.

In local, I know the `npm install` create diff' only for `package-lock.json` but without any change _(no whitespace)_, I suppose in distant server also, but I can't find solution for avoid that.

**Comment by borisdamevin** [comment]
Ok, founded.

All external dependencies used by each packages need to be declared on root mono repo `package.json`.
