### ISSUE TITLE
Strange behavior of the `latch` option

### ISSUE THREAD

**Issue by Ikilonchic** [ext/semantic-release-lerna#84]
Hi, @ext.

I found strange behavior in the `latch` option. If you publish a new version of the project on prerelease branches, this option doesn't work, but it's fine on the default branch.

This option includes `major`, `minor`, `fix`, and `none` values, and as I try it, the pre-release version does not fall under any of them.

Is this a bug or a feature of the behavior?

**Comment by ext** [comment]
That sounds like a bug 😊 There is no code to handle that case but what I would expect is that all packages would be released and all dependencies between packages be updated with the prerelease version. Does that match what you would expect?

Currently I'm very short on time so a pull request would be awesome.

**Comment by Ikilonchic** [comment]
Sure, no problem. I have already created a PR with my suggestions.
