### ISSUE TITLE
@semantic-release/npm version 10 no longer supports using set-legacy-token

### ISSUE THREAD

**Issue by ScottMorris** [ext/semantic-release-lerna#91]
I recently upgraded our packages and to Node 18 and ran into an issue when trying to publish.  _semantic-release-lerna_ uses the `set-legacy-token` module from _@semantic-release/npm_ and it appears they have removed that file from their project.

The message that I get when trying to publish:

```
[semantic-release] › ✘  An error occurred while running semantic-release: Error: Cannot find module '@semantic-release/npm/lib/set-legacy-token'
```

Upon investigating this error, it turns out the _@semantic-release/npm_  package no longer uses or contains the `set-legacy-token.js` file, as it was [removed back in January 2023](https://github.com/semantic-release/npm/commit/51ab3c8b7bf6848080288a64af1b723ebf267ba6#diff-768d370764ceded1f51fa9e7eab5304f3dcd6e1b913bac59399e8940ed688cdf) and is a breaking change in version 10.

In _semantic-release-lerna_, this file is [directly imported and called](https://github.com/ext/semantic-release-lerna/blob/1c1b5508d6c6ad809ed351dde34110ad9c59dca4/index.js#L3) within the `index.js` a number of times in different stages.  Looking more into what `set-legacy-token` does, it appear that it is only used to set the `LEGACY_TOKEN` env var, so perhaps it can be skipped since _@semantic-release/npm_ no longer supports this?

A [copy of the `set-legacy-token.js`](https://github.com/semantic-release/npm/blob/c5036aab32f3488698383448baf58ce3b1038b61/lib/set-legacy-token.js):
```js
export default function ({ env }) {
  // Set the environment variable `LEGACY_TOKEN` when user use the legacy auth, so it can be resolved by npm CLI
  if (env.NPM_USERNAME && env.NPM_PASSWORD && env.NPM_EMAIL) {
    env.LEGACY_TOKEN = Buffer.from(`${env.NPM_USERNAME}:${env.NPM_PASSWORD}`, "utf8").toString("base64");
  }
}
```

**Comment by ext** [comment]
Yes, thank you for reporting this. I'm aware and I think the correct course of action is to drop support just as upstream have done.

If you are able to create a pull request it would be much appreciated.

**Comment by ScottMorris** [comment]
Thanks for the guidance. I was about to whip one up when my new router came and I have good internet again 😅!

I'll submit one shortly with the updates.

**Comment by ScottMorris** [comment]
I'm wondering what you think about bumping up some of the dependent versions, as the upstream has moved to Node 18?

For example, _semantic-release_ version `20.1.3` requires Node 18+:

```
npm WARN EBADENGINE Unsupported engine {
npm WARN EBADENGINE   package: 'semantic-release@20.1.3',
npm WARN EBADENGINE   required: { node: '>=18' },
npm WARN EBADENGINE   current: { node: 'v16.20.0', npm: '8.19.4' }
npm WARN EBADENGINE }
```

The `package.json` file currently lists the minimum version as Node 14

```json
  "engines": {
    "node": ">= 14"
  },
```

**Comment by ext** [comment]
> @ext, I'm wondering what you think about bumping up some of the dependent versions, as the upstream has moved to Node 18?

Would make sense to follow the upstream requirements right?

**Comment by ScottMorris** [comment]
I agree, I'm still looking into this.  It appears in order to use the newer upstream changes this lib needs to be an ESM lib.  This conversion is new to me so I'm learning a lot but it's also a bit confusing updating some of the uses of `require` to using that ESM expects.

I'll keep you updated.

**Comment by ScottMorris** [comment]
I'm wondering if you're able to explain a bit more about this line, [line 72 in `integration.test.js`](https://github.com/ext/semantic-release-lerna/blob/1c1b5508d6c6ad809ed351dde34110ad9c59dca4/test/integration.test.js#L72):

```js
sut = await require("..");
```

Since it is using `require` it is giving me grief.

**Comment by ScottMorris** [comment]
Update: I got past that issue, but I'm stuck at trying to figure out how the tests generate the `.npmrc` file contents.  There appears to be a bug there, ``_auth` must be renamed to `//localhost:4873/:_auth` in user config,` and this is eluding me.

I've narrowed it down the the `setNpmrcAuth` call in `verify-auth.js` but it uses something called [`rc`](https://github.com/dominictarr/rc) that seems to magically pull the information from somewhere.

If anyone has any ideas that might be helpful.

**Comment by ext** [comment]
> I'm wondering if you're able to explain a bit more about this line, [line 72 in `integration.test.js`](https://github.com/ext/semantic-release-lerna/blob/1c1b5508d6c6ad809ed351dde34110ad9c59dca4/test/integration.test.js#L72):
> 
> ```js
> sut = await require("..");
> ```
> 
> Since it is using `require` it is giving me grief.

That would be that it tries to import the package itself, e.g. same as `require("../index.js")`. I don't remember if it has to be reimported for every test run or if you can move it up to the top of the file. You can probably move it and replace it with `import sut from "../index.js"`.

> Update: I got past that issue, but I'm stuck at trying to figure out how the tests generate the `.npmrc` file contents. There appears to be a bug there, ``_auth`must be renamed to`//localhost:4873/:_auth` in user config,` and this is eluding me.
> 
> I've narrowed it down the the `setNpmrcAuth` call in `verify-auth.js` but it uses something called [`rc`](https://github.com/dominictarr/rc) that seems to magically pull the information from somewhere.
> 
> If anyone has any ideas that might be helpful.

Is that still needed if `NPM_TOKEN` is set? The code that used to set `_auth` has been removed from `@semantic-
release/npm` in [51ab3c](https://github.com/semantic-release/npm/commit/51ab3c8b7bf6848080288a64af1b723ebf267ba6)

If it is for the tests only maybe manually creating the `.npmrc` file would be an option?

**Comment by ScottMorris** [comment]
I'm still looking through this, and I got around the issue I was facing in the last comment with the `npmrc` file.  I'm not sure what it was but I've been systematically reworking the project from the ground up.

> That would be that it tries to import the package itself

I noticed this wasn't actually required before each test so I moved it to an import that imported the `index.js` file.

I'm currently stuck on trying to mock out `execa` within the `lib/verify-git.test.js` file.  Since it is now using ESM, Jest is a bit more messy to mock with as their support is limited and I'm having issues trying to understand how it should be put together since their documentation is spotty and most are mocking their own files (ie. `./someFile` within their own project) and not imported modules.

I have most of the `integration.test.js` tests working, and the last things I need to do in this new branch I'm working on is to update the other `*.test.js` files to support ESM as well as upgrade the underlying packages to bring them inline with upstream.

My current work can be found in the [convert-to-esm](https://github.com/ScottMorris/semantic-release-lerna/tree/convert-to-esm) branch in my own fork.  There are a number of items for cleanup as I work through this process.  The changes to `verify-git.test.js` aren't committed as they are in progress and non functional.

Running the tests can be done via `NODE_OPTIONS=--experimental-vm-modules npm run test`

I'm putting here some resources I've looked at for reference:

- https://jestjs.io/docs/ecmascript-modules
- https://stackoverflow.com/a/73249957
- https://www.sitepen.com/blog/jest-esm-almost-there

**Comment by ScottMorris** [comment]
A quick and easy workaround is to install `@semantic-release/npm@9.0.2` within one's project.  This seems to hold NPM back from install v10 and thus doesn't have any of the new updates yet that break the current released version of `semantic-release-lerna`.

```
npm i -D @semantic-release/npm@9.0.2
```

**Comment by ext** [comment]
Hi, sorry for taking long to get back to you, thank you for your hard work!

I'm preparing a pull request to drop support for legacy token and some other preparatory fixes (such as making sure eslint will run after ESM migration). After that maybe we could rebase your branch and fix the eventual missing parts?

**Comment by ext** [comment]
> Update: I got past that issue, but I'm stuck at trying to figure out how the tests generate the `.npmrc` file contents. There appears to be a bug there, ``_auth`must be renamed to`//localhost:4873/:_auth` in user config,` and this is eluding me.

I've merged some changes to how the user for the tests are being created and `_auth` has been renamed to `//localhost:4873/_authToken`.

**Comment by ScottMorris** [comment]
Hi, thanks for the update! I'll try and see how it goes rebasing my work with these new changes.

Getting Jest to work was proving to be a challenge, so I took a short break.

**Comment by ext** [comment]
It might not be the right approach but maybe we could use `babel-jest` instead of native esm for tests?

It should work out-of-the-box after adding `@babel/core` and `@babel/preset-env` and a configuration `babel.config.cjs` with:

```js
module.exports = {
    presets: ["@babel/preset-env"],
};
```

Would be nice to have native ESM for the tests as well though but if that's the only thing holding ESM support back maybe it would work as an intermediate step?

**Comment by ScottMorris** [comment]
Thanks @ext! Sorry for the delay, I didn't find any free cycles yet.  Looks like you got things working 😄

**Comment by ext** [comment]
No problem, I'm very grateful for your efforts, you helped to uncover lots of issues such as the auth tokens, testing etc which really helped a lot when migrating.

Let me know if you run into any issues with the new release!
